#!/usr/bin/env python3
"""
Step 16: Comparison Tables Validators (WIP)

WIP validators for Step 16 (create comparison tables). These perform conservative
checks on the Excel workbook generated by Step 16.

Author: Data Pipeline
Date: 2025-09-17
"""

import glob
from pathlib import Path
from typing import Dict, Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def validate_step16_files(data_dir: str = "output") -> Dict[str, Any]:
    """Validate presence of Step 16 Excel workbook (WIP)."""
    base = Path(data_dir)
    pattern = str(base / "spreadsheet_comparison_analysis_*_*.xlsx")
    matches = sorted(glob.glob(pattern), key=lambda p: Path(p).stat().st_mtime, reverse=True)

    out: Dict[str, Any] = {
        "validation_passed": False,  # Requires real data validation
        "files": {
            "excel_workbook": matches[0] if matches else None,
            "count": len(matches)
        },
        "errors": [],
        "warnings": [],
        "statistics": {"validation_timestamp": datetime.now().isoformat()}
    }

    if not matches:
        out["warnings"].append("No Step 16 workbook found matching spreadsheet_comparison_analysis_*_*.xlsx")
        return out

    # Basic file checks
    workbook = Path(matches[0])
    try:
        size_mb = round(workbook.stat().st_size / (1024 * 1024), 3)
        out["statistics"]["excel_file_size_mb"] = size_mb
        if size_mb <= 0:
            out["errors"].append("Workbook size is zero")
            out["validation_passed"] = False
    except Exception as e:
        out["errors"].append(f"Failed to stat workbook: {str(e)}")
        out["validation_passed"] = False

    return out


def validate_step16_complete(data_dir: str = "output") -> Dict[str, Any]:
    logger.info("Starting Step 16 WIP validation using data_dir=%s", data_dir)
    return validate_step16_files(data_dir)


__all__ = [
    'validate_step16_files',
    'validate_step16_complete'
]
